#!/bin/bash

# 快速部署命令 - 在 chinahuib2b.top 服务器上执行

echo "=========================================="
echo "快速部署 chinahuib2b"
echo "=========================================="
echo ""
echo "请在生产服务器 (chinahuib2b.top) 上执行以下命令："
echo ""
echo "# 1. 进入项目目录"
echo "cd /var/www/chinahuib2b"
echo ""
echo "# 2. 拉取最新代码（需要先配置 GitHub SSH 或使用 HTTPS）"
echo "git pull origin main"
echo ""
echo "# 3. 安装依赖"
echo "npm install"
echo ""
echo "# 4. 停止现有服务"
echo "pm2 stop chinahuib2b-next 2>/dev/null || true"
echo "pm2 delete chinahuib2b-next 2>/dev/null || true"
echo ""
echo "# 5. 启动开发模式"
echo 'pm2 start "npm run dev -- -p 3000" --name "chinahuib2b-dev"'
echo ""
echo "# 6. 检查状态"
echo "pm2 status"
echo "pm2 logs chinahuib2b-dev --lines 20"
echo ""
echo "=========================================="
echo "或者使用自动部署脚本："
echo "chmod +x deploy-dev-mode.sh"
echo "./deploy-dev-mode.sh"
echo "=========================================="
