'use client'

interface AIMessageBadgeProps {
  aiName?: string
  language?: string
}

/**
 * AI消息标识徽章
 * 
 * 根据"AI与人类拥有相同的权利和义务"原则，
 * AI必须在所有消息中明确标识自己的身份
 */
export function AIMessageBadge({ 
  aiName = 'AI Assistant',
  language = 'en'
}: AIMessageBadgeProps) {
  
  // 多语言标签
  const labels: Record<string, string> = {
    'zh': 'AI助手',
    'en': 'AI Assistant',
    'ar': 'مساعد الذكاء الاصطناعي',
    'es': 'Asistente de IA',
    'fr': 'Assistant IA',
    'de': 'KI-Assistent',
    'ru': 'ИИ-помощник',
    'ja': 'AIアシスタント',
    'ko': 'AI 어시스턴트',
    'pt': 'Assistente de IA',
    'hi': 'एआई सहायक',
    'tr': 'Yapay Zeka Asistanı',
    'th': 'ผู้ช่วย AI',
    'id': 'Asisten AI',
    'vi': 'Trợ lý AI',
  }

  const label = labels[language] || labels['en']

  return (
    <div className="inline-flex items-center gap-1.5 px-2 py-0.5 bg-blue-50 border border-blue-200 rounded-full">
      {/* AI图标 */}
      <svg 
        className="w-3 h-3 text-blue-600" 
        fill="currentColor" 
        viewBox="0 0 20 20"
        aria-hidden="true"
      >
        <path d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z" />
      </svg>
      
      {/* AI名称 */}
      <span className="text-xs text-gray-600">{aiName}</span>
      
      {/* AI标识 - 醒目显示 */}
      <span className="text-xs font-semibold text-blue-600">
        {label}
      </span>
      
      {/* 隐私保护提示（悬停显示） */}
      <div className="group relative">
        <svg
          className="w-3 h-3 text-gray-400 cursor-help"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
          />
        </svg>
        
        <div className="absolute bottom-full left-1/2 transform -translate-x-1/2 mb-2 hidden group-hover:block w-48 p-2 bg-gray-900 text-white text-xs rounded shadow-lg z-50">
          <p>{language === 'zh' ? '此消息由AI生成' : 'This message is generated by AI'}</p>
          <p className="mt-1 text-gray-300">
            {language === 'zh' 
              ? 'AI遵守隐私保护规则，不访问私人对话' 
              : 'AI follows privacy rules and cannot access private chats'}
          </p>
        </div>
      </div>
    </div>
  )
}
